// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {generator} from '../models';
import {app} from '../models';

export function CancelGeneration():Promise<void>;

export function DefaultConfig():Promise<generator.GeneratorConfig>;

export function Generate(arg1:generator.GeneratorConfig):Promise<generator.Report>;

export function LastReport():Promise<generator.Report>;

export function LoadConfig(arg1:string):Promise<generator.GeneratorConfig>;

export function LoadSchema(arg1:Array<string>):Promise<app.SchemaSummary>;

export function Progress():Promise<app.Progress>;

export function SaveConfig(arg1:string,arg2:generator.GeneratorConfig):Promise<void>;

export function SelectOutputPath():Promise<string>;

export function SelectSchemaFiles():Promise<Array<string>>;
