// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGeneration() {
  return window['go']['app']['Service']['CancelGeneration']();
}

export function DefaultConfig() {
  return window['go']['app']['Service']['DefaultConfig']();
}

export function Generate(arg1) {
  return window['go']['app']['Service']['Generate'](arg1);
}

export function LastReport() {
  return window['go']['app']['Service']['LastReport']();
}

export function LoadConfig(arg1) {
  return window['go']['app']['Service']['LoadConfig'](arg1);
}

export function LoadSchema(arg1) {
  return window['go']['app']['Service']['LoadSchema'](arg1);
}

export function Progress() {
  return window['go']['app']['Service']['Progress']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['app']['Service']['SaveConfig'](arg1, arg2);
}

export function SelectOutputPath() {
  return window['go']['app']['Service']['SelectOutputPath']();
}

export function SelectSchemaFiles() {
  return window['go']['app']['Service']['SelectSchemaFiles']();
}
